### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'prev_layer'

### ISSUE THREAD

**Issue by peach2wanzi** [GuangmingZhu/Conv3D_CLSTM#13]
I have replaced RNNLayer code with the tensorlayer-rnnlayer.py.But now it have a new problem.

 I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: FMA
[TL] WARNING: Function: `tensorlayer.layers.utils.set_name_reuse` (in file: /home/fang/3Dgesture/tensorlayer/layers/utils.py) is deprecated and will be removed after 2018-06-30.
Instructions for updating: TensorLayer relies on TensorFlow to check name reusing

[TL] WARNING: this method is DEPRECATED and has no effect, please remove it from your code.
[TL] WARNING: DeprecationWarning: BatchNormLayer.__init__(): `layer` argument is deprecated and will be removed in version 1.9, please change for `prev_layer.`
[TL] WARNING: DeprecationWarning: BatchNormLayer.__init__(): `layer` argument is deprecated and will be removed in version 1.9, please change for `prev_layer.`
[TL] WARNING: DeprecationWarning: BatchNormLayer.__init__(): `layer` argument is deprecated and will be removed in version 1.9, please change for `prev_layer.`
Traceback (most recent call last):
  File "training_skig_rgb.py", line 49, in <module>
    networks = net.c3d_clstm(x, num_classes, False, True)
  File "/home/fang/3Dgesture/c3d_clstm.py", line 86, in c3d_clstm
    name='clstm_layer_1')
  File "/home/fang/3Dgesture/tensorlayer/layers/recurrent.py", line 55, in __init__
    Layer.__init__(self, name=name)
  File "/home/fang/3Dgesture/tensorlayer/decorators/deprecated_alias.py", line 24, in wrapper
    return f(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'prev_layer'

I erally don't know where is the point.....

**Comment by peach2wanzi** [comment]
@GuangmingZhu  Thank you!!!

**Comment by GuangmingZhu** [comment]
@peach2wanzi This work is done with the old version of Tensorlayer. You can refer to the new network using keras in TF-1.2: https://github.com/GuangmingZhu/ContinuousGR and https://github.com/GuangmingZhu/AttentioninConvLSTM.
